### PR TITLE
Using I18n.default_locale when have no translation

### PR DESCRIPTION
**Pull request by jerrygreen**
Am I the first who needs this? Anyway... Thanks for the gem!

### CODE REVIEW

**Comment by bithavoc** [comment]
Hey jerry, thanks for this PR.
I noticed this in the CI:

```
1) Multilang should set/get some attributes in/from PartialrPost
     Failure/Error: rp.title.should == ""
       expected: ""
            got: "Latvie?u nosaukums" (using ==)
     # ./spec/multilang_spec.rb:222:in `block (2 levels) in <top (required)>'
```

**Comment by JerryGreen** [comment]
Yea. For some reason I can't run `rspec` command. Got this:

```
/home/vagrant/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize': fe_sendauth: no password supplied (PG::ConnectionBad)
```

I was too lazy to figure it out (and I still am) so I just did the pull request. Sorry me.

Anyway, attempt number 2, wish me luck :D

**Comment by JerryGreen** [comment]
That's not exactly the same that I wanted initially.

Initially, I wanted to get values in the order like `current_locale > default_locale > nil`.

Now it's like `current_locale > default_locale > any available_locale > nil`. Still better.

**Comment by bithavoc** [comment]
can you rebase against master and squash these commits? there should be only one commit in this PR :dart:

**Comment by jerrygreen** [comment]
Did it. Also added a new method `current_or_default` (my initial idea) with little fix in README. I am happy. And you?

**Comment by bithavoc** [comment]
Better. Thanks.

**Pull request merged**
